scene_info = [
	[cutscene_instance_create, obj_player.x+320, obj_player.y, obj_baxter],
	[cutscene_play_music, Somewhere__Someday],
	[move_character, obj_player,  200,0, true, 1],
	[dialogue, DISPLAY.NORMAL, {text: "It's completely empty. Every house, every \nstore...",name:"Baxter"}],
	[dialogue, DISPLAY.NORMAL, {text: "Do you sense anything Lyraka?", name: "Baxter"}],
	[move_character, obj_baxter, -60, 0, true, 1],
	[cutscene_wait, 2],
	[cutscene_play_music, undefined],
	[cutscene_play_soundeffect, dialga],
	[dialogue, DISPLAY.NORMAL, {text: "SAY SOMETHING YOU DUMB CAT!!!", name: "Baxter"}],
	[dialogue, DISPLAY.NORMAL, {text: "Quit acting like you don't know what's\n going on! YOU ARE A GOD!", name: "Baxter"}],
	[cutscene_wait, .5],
	[cutscene_play_soundeffect, WAVE_SE_049],
	[move_character, obj_player, obj_player.x - 70, 0, true, 3],
	[cutscene_wait, 2],
	[dialogue, DISPLAY.NORMAL, {text: "I don't get it. Is this some test or a sick joke?", name: "Baxter"}],
	[cutscene_instance_create, obj_player.x+200, obj_player.y-200, obj_ninja],
	[cutscene_wait, 1],
	[move_character, obj_ninja,  0,200, true, 4],
	[cutscene_play_soundeffect, _031___What_],
	[cutscene_wait, .5],
	[cutscene_play_music, _80__Deep_Within_Team_Galactic_HQ],
	[dialogue, DISPLAY.NORMAL, {text: "Lyraka!!", name: "Baxter"}],
	[cutscene_wait, .5],
	[dialogue, DISPLAY.NORMAL, {text: "Hey! Leaver it alone! I found it first!", name: "Baxter"}],
	[cutscene_play_music, undefined],
	[cutscene_wait, 3],
	[dialogue, DISPLAY.NORMAL, {text: "Then perish..", name: "????"}],
	[new_encounter, [global.enemies.ninja]],
	[cutscene_instance_destroy, obj_baxter],
	[cutscene_instance_destroy, obj_ninja],
]