scene_info = [
	[cutscene_instance_create, obj_player.x+320, obj_player.y, obj_baxter],
	[cutscene_play_music, Somewhere__Someday],
	[move_character, obj_player,  200,0, true, 1.5],
	[dialogue, DISPLAY.NORMAL, {text: "It's completely empty. Every house, every \nstore...",name:"Baxter"}],
	[dialogue, DISPLAY.NORMAL, {text: "Do you sense anything Lyraka?", name: "Baxter"}],
	[move_character, obj_baxter, -55, 0, true, 1],
	[cutscene_wait, 2],
	
	//[cutscene_play_soundeffect, dialga],
	[dialogue, DISPLAY.NORMAL, {text: "What are you staring for? Won't you answer \n my question?", name: "Baxter"}],
	[dialogue, DISPLAY.NORMAL, {text: "You haven't said a word since I found you.\n Are you-", name: "Baxter"}],
	[cutscene_play_music, undefined],
	[cutscene_wait, 1.5],
	[cutscene_play_soundeffect, WAVE_SE_049],
	[cutscene_object_change_sprite, obj_player, spr_Lusaka_Down],
	[move_character, obj_player, obj_player.x - 70, 0, true, 3],
	[cutscene_wait, 2],
	[dialogue, DISPLAY.NORMAL, {text: "Huh? What is it?", name: "Baxter"}],
	[cutscene_instance_create, obj_player.x+200, obj_player.y-200, obj_ninja],
	[cutscene_wait, 1],
	[move_character, obj_ninja,  0,200, true, 4],
	[cutscene_wait, .1],
	[cutscene_object_change_sprite, obj_player, spr_lusaka_walk],
	[move_character, obj_player, obj_player.x + 30, 0, true, 3],
	[cutscene_play_soundeffect, _031___What_],
	[cutscene_expression, obj_baxter, spr_exclamation],
	//[cutscene_wait, .5],
	[cutscene_play_music, _80__Deep_Within_Team_Galactic_HQ],
	//[cutscene_object_change_sprite, obj_player, spr_lusaka_walk, 12],
	[dialogue, DISPLAY.NORMAL, {text: "Lyraka!!", name: "Baxter"}],
	[cutscene_wait, .5],
	[dialogue, DISPLAY.NORMAL, {text: "Hey! Leaver it alone! I found it first!", name: "Baxter"}],
	[cutscene_play_music, undefined],
	[cutscene_wait, 1],
	[dialogue, DISPLAY.NORMAL, {text: "The Turning Point was never yours to \n begin with", name: "????"}],
	[cutscene_instance_destroy, obj_baxter],
	[cutscene_instance_destroy, obj_ninja],
	[new_encounter, [global.enemies.ninja]],
]